import {
  AppKPIs,
  DamagedStockRecord,
  DecisionReplayRecord,
  ExperimentItem,
  ForecastDay,
  InventoryItem,
  LeftoverFeedbackRecord,
  OrganizationType,
  ProductionPlanItem,
  RescuePlanItem,
  SmartMenuItem,
  TodayActionCard,
} from './types';

export interface AppStateData {
  kpis: AppKPIs;
  todayActions: TodayActionCard[];
  forecastDays: ForecastDay[];
  productionPlans: ProductionPlanItem[];
  inventory: InventoryItem[];
  rescuePlans: RescuePlanItem[];
  smartMenus: SmartMenuItem[];
  experiments: ExperimentItem[];
  decisionReplays: DecisionReplayRecord[];
  leftoverHistory: LeftoverFeedbackRecord[];
  damagedStock: DamagedStockRecord[];
  weatherInfo: {
    city: string;
    temperature: string;
    condition: string;
    isRainExpected: boolean;
  };
  localNotice: string;
}

export function getDefaultDemoData(orgType: OrganizationType = 'cafeteria'): AppStateData {
  const orgConfigs: Record<OrganizationType, { customers: number; riskKg: number; avoidedKg: number; costSaving: number; notice: string }> = {
    cafeteria: {
      customers: 185,
      riskKg: 6.8,
      avoidedKg: 4.2,
      costSaving: 1240,
      notice: 'College cultural festival prep in main auditorium; evening footfall may extend by 30 mins.',
    },
    restaurant: {
      customers: 140,
      riskKg: 5.4,
      avoidedKg: 3.8,
      costSaving: 1480,
      notice: 'Evening dine-in rush expected; 2 large group reservations confirmed for dinner service.',
    },
    hostel: {
      customers: 220,
      riskKg: 8.2,
      avoidedKg: 5.6,
      costSaving: 1650,
      notice: 'Exam study week; evening mess attendance expected to increase by ~25 students.',
    },
    supermarket: {
      customers: 340,
      riskKg: 12.5,
      avoidedKg: 9.1,
      costSaving: 3100,
      notice: 'Fresh produce crate intake arriving at 3:30 PM; bakery shelf expiry alert at 7:00 PM.',
    },
    hotel: {
      customers: 160,
      riskKg: 7.5,
      avoidedKg: 4.8,
      costSaving: 2100,
      notice: 'Corporate banquet buffet scheduled for 85 guests; breakfast buffet replenishment calibrated.',
    },
    other: {
      customers: 150,
      riskKg: 6.0,
      avoidedKg: 4.0,
      costSaving: 1300,
      notice: 'Central catering kitchen dispatch ready; lunch thali routing calibrated.',
    },
  };

  const cfg = orgConfigs[orgType] || orgConfigs.cafeteria;

  return {
    kpis: {
      customersExpected: cfg.customers,
      foodAtRiskKg: cfg.riskKg,
      potentialWasteAvoidedKg: cfg.avoidedKg,
      potentialCostSaving: cfg.costSaving,
    },
    todayActions: [
      {
        id: 'act-1',
        item: 'RICE',
        emoji: '🍚',
        actionHeading: 'PREPARE 23–24 KG RICE',
        subheading: 'Adjusted for rainy evening & yesterday’s 2.1 kg surplus',
        reasons: [
          'Demand is 6% lower on similar days',
          'Yesterday had 2.1 kg leftover in kitchen',
          'Rain is expected this evening in Bengaluru',
          '4 kg rice is already prepared/available in hot hold',
        ],
        potentialWasteAvoidedKg: 1.5,
        costSaved: 220,
        confidencePct: 88,
        risksIfIgnored: 'Surplus rice of ~2.5 kg will turn starchy and spoil by closing time.',
        alternatives: 'Hold 3 kg uncooked rice in dry bin for quick 15-minute replenishment if dinner surges.',
        status: 'pending',
      },
      {
        id: 'act-2',
        item: 'TOMATOES',
        emoji: '🍅',
        actionHeading: "DON'T BUY MORE TOMATOES",
        subheading: '12 kg stock already available; 6 kg may expire unused',
        reasons: [
          '12 kg currently stored in walk-in cooler',
          'Shelf life ends in 48 hours (batch #TM-894)',
          'Average consumption is 4.5 kg/day',
          '6 kg may remain unused before expiry without intervention',
        ],
        potentialWasteAvoidedKg: 5.5,
        costSaved: 380,
        confidencePct: 94,
        risksIfIgnored: 'Vendor delivery of 10 kg will push older stock into spoilage.',
        alternatives: 'Use tomatoes in today’s approved lunch menu or batch into tomato rasam/puree.',
        status: 'pending',
      },
      {
        id: 'act-3',
        item: 'PANEER',
        emoji: '🥛',
        actionHeading: 'USE PANEER TODAY',
        subheading: '8 kg near expiry — activate today’s lunch special',
        reasons: [
          'Batch #PN-201 expires tomorrow at 11:00 AM',
          'Refrigeration temperature stable but near 72-hour dairy limit',
          'High cost ingredient (₹320/kg)',
          'Zero risk of waste if incorporated into lunch curry or roll special',
        ],
        potentialWasteAvoidedKg: 6.0,
        costSaved: 1920,
        confidencePct: 91,
        risksIfIgnored: '8 kg spoiled paneer represents ₹2,560 dead loss tomorrow.',
        alternatives: 'Freeze paneer cubes or move 4 kg to Hostel Dining Hall 2.',
        status: 'pending',
      },
    ],
    forecastDays: [
      {
        dayName: 'Mon',
        dateStr: 'Yesterday',
        expectedCustomers: 180,
        expectedMeals: 210,
        keyIngredientDemand: [
          { item: 'Rice', amountKg: 24 },
          { item: 'Dal', amountKg: 10 },
          { item: 'Veggies', amountKg: 12 },
        ],
      },
      {
        dayName: 'Tue',
        dateStr: 'Previous',
        expectedCustomers: 192,
        expectedMeals: 225,
        keyIngredientDemand: [
          { item: 'Rice', amountKg: 25 },
          { item: 'Dal', amountKg: 11 },
          { item: 'Veggies', amountKg: 13 },
        ],
      },
      {
        dayName: 'Wed',
        dateStr: 'Today',
        expectedCustomers: 185,
        expectedMeals: 215,
        isToday: true,
        keyIngredientDemand: [
          { item: 'Rice', amountKg: 23 },
          { item: 'Dal', amountKg: 9 },
          { item: 'Veggies', amountKg: 11 },
        ],
      },
      {
        dayName: 'Thu',
        dateStr: 'Tomorrow',
        expectedCustomers: 210,
        expectedMeals: 245,
        keyIngredientDemand: [
          { item: 'Rice', amountKg: 27 },
          { item: 'Dal', amountKg: 12 },
          { item: 'Veggies', amountKg: 14 },
        ],
      },
      {
        dayName: 'Fri',
        dateStr: 'Friday',
        expectedCustomers: 230,
        expectedMeals: 270,
        keyIngredientDemand: [
          { item: 'Rice', amountKg: 29 },
          { item: 'Dal', amountKg: 13 },
          { item: 'Veggies', amountKg: 16 },
        ],
      },
      {
        dayName: 'Sat',
        dateStr: 'Weekend',
        expectedCustomers: 140,
        expectedMeals: 160,
        keyIngredientDemand: [
          { item: 'Rice', amountKg: 18 },
          { item: 'Dal', amountKg: 7 },
          { item: 'Veggies', amountKg: 9 },
        ],
      },
      {
        dayName: 'Sun',
        dateStr: 'Weekend',
        expectedCustomers: 95,
        expectedMeals: 110,
        keyIngredientDemand: [
          { item: 'Rice', amountKg: 13 },
          { item: 'Dal', amountKg: 5 },
          { item: 'Veggies', amountKg: 6 },
        ],
      },
    ],
    productionPlans: [
      {
        id: 'pp-1',
        item: 'Rice',
        emoji: '🍚',
        demandKg: 24,
        usableStockKg: 3,
        recommendedProductionKg: 21,
        unit: 'kg',
        explanation: 'Customer demand requires 24 kg. You already have 3 kg usable stock from early steam batch. Prepare 21 kg.',
        status: 'pending',
      },
      {
        id: 'pp-2',
        item: 'Chicken Curry',
        emoji: '🍗',
        demandKg: 16,
        usableStockKg: 2,
        recommendedProductionKg: 14,
        unit: 'kg',
        explanation: 'Demand projection is 16 kg. 2 kg is pre-cooked in refrigerator. Prepare 14 kg fresh batch.',
        status: 'pending',
      },
      {
        id: 'pp-3',
        item: 'Vegetables / Sabzi',
        emoji: '🥬',
        demandKg: 10,
        usableStockKg: 7,
        recommendedProductionKg: 3,
        unit: 'kg',
        explanation: 'Demand is 10 kg. 7 kg cooked mixed seasonal veg is ready from morning service. Prepare only 3 kg.',
        status: 'pending',
      },
      {
        id: 'pp-4',
        item: 'Dal Tadka',
        emoji: '🍲',
        demandKg: 12,
        usableStockKg: 3,
        recommendedProductionKg: 9,
        unit: 'kg',
        explanation: '12 kg expected consumption across thalis. 3 kg available. Recommended 9 kg prep.',
        status: 'accepted',
      },
    ],
    inventory: [
      {
        id: 'inv-1',
        name: 'Tomatoes',
        emoji: '🍅',
        currentStock: 12,
        unit: 'kg',
        batchNumber: 'TM-894',
        purchaseDate: '28 Sep 2026',
        expiryDate: '05 Oct 2026',
        daysRemaining: 2,
        expectedDailyUsage: 4,
        expectedSurplus: 4,
        riskLevel: 'HIGH',
        lifecycleStage: 'available',
        suggestedAction: 'Use 3–4 kg in today’s menu or prepare tomato rasam.',
        costPerUnit: 35,
      },
      {
        id: 'inv-2',
        name: 'Fresh Paneer',
        emoji: '🥛',
        currentStock: 8,
        unit: 'kg',
        batchNumber: 'PN-201',
        purchaseDate: '01 Oct 2026',
        expiryDate: '04 Oct 2026',
        daysRemaining: 1,
        expectedDailyUsage: 3,
        expectedSurplus: 5,
        riskLevel: 'CRITICAL',
        lifecycleStage: 'available',
        suggestedAction: 'Near expiry. Launch Paneer Special or freeze cubes.',
        costPerUnit: 320,
      },
      {
        id: 'inv-3',
        name: 'Basmati Rice',
        emoji: '🍚',
        currentStock: 45,
        unit: 'kg',
        batchNumber: 'RC-402',
        purchaseDate: '15 Sep 2026',
        expiryDate: '15 Nov 2026',
        daysRemaining: 42,
        expectedDailyUsage: 22,
        expectedSurplus: 0,
        riskLevel: 'LOW',
        lifecycleStage: 'stored',
        suggestedAction: 'Safe dry storage. Rotate with FEFO rules.',
        costPerUnit: 65,
      },
      {
        id: 'inv-4',
        name: 'Leafy Spinach',
        emoji: '🥬',
        currentStock: 6,
        unit: 'kg',
        batchNumber: 'SP-331',
        purchaseDate: '02 Oct 2026',
        expiryDate: '04 Oct 2026',
        daysRemaining: 1,
        expectedDailyUsage: 2.5,
        expectedSurplus: 3.5,
        riskLevel: 'HIGH',
        lifecycleStage: 'available',
        suggestedAction: 'Incorporate into Palak Dal before leaves wilt.',
        costPerUnit: 40,
      },
      {
        id: 'inv-5',
        name: 'Chicken Breast / Curry Cut',
        emoji: '🍗',
        currentStock: 14,
        unit: 'kg',
        batchNumber: 'CK-109',
        purchaseDate: '02 Oct 2026',
        expiryDate: '04 Oct 2026',
        daysRemaining: 1,
        expectedDailyUsage: 12,
        expectedSurplus: 2,
        riskLevel: 'MEDIUM',
        lifecycleStage: 'available',
        suggestedAction: 'Marinate today; cook full batch for lunch rush.',
        costPerUnit: 190,
      },
      {
        id: 'inv-6',
        name: 'Cooking Oil',
        emoji: '🛢️',
        currentStock: 30,
        unit: 'L',
        batchNumber: 'OL-901',
        purchaseDate: '20 Sep 2026',
        expiryDate: '20 Dec 2026',
        daysRemaining: 78,
        expectedDailyUsage: 3,
        expectedSurplus: 0,
        riskLevel: 'LOW',
        lifecycleStage: 'stored',
        suggestedAction: 'Dry storage safe. Adequate stock for 10 days.',
        costPerUnit: 140,
      },
    ],
    rescuePlans: [
      {
        id: 'resc-1',
        ingredient: 'Tomatoes (Batch #TM-894)',
        emoji: '🍅',
        quantityAtRiskKg: 6.8,
        expiryHours: 36,
        currentRisk: 'HIGH',
        primarySuggestedTier: 'USE',
        status: 'pending',
        tiers: [
          {
            tierNumber: 1,
            tierName: 'USE',
            title: 'Use in today’s existing lunch menu',
            description: 'Incorporate 4 kg tomatoes into the scheduled lunch curry and sambar base without menu changes.',
            isFeasible: true,
            impactScore: 'Rescues 4.0 kg immediately (₹140 value)',
            safetyStatus: '100% Safe (within 48h shelf life)',
            actionLabel: 'Execute Kitchen Use',
          },
          {
            tierNumber: 2,
            tierName: 'ALLOCATE',
            title: 'Move 3 kg to Hostel Dining Hall 2',
            description: 'Hostel Dining Hall 2 is experiencing a 3.5 kg shortage for evening dinner service (Distance: 1.2 km).',
            isFeasible: true,
            impactScore: 'Rescues 3.0 kg (Zero transport cost)',
            safetyStatus: 'Chilled transit container verified',
            actionLabel: 'Approve Transfer',
          },
          {
            tierNumber: 3,
            tierName: 'PROMOTE',
            title: 'Promote 20% discount on Tomato Soup',
            description: 'Offer an add-on soup bowl at ₹30 during lunch service to drive immediate customer uptake.',
            isFeasible: true,
            impactScore: 'Recovers ₹600 extra revenue',
            safetyStatus: 'Cooked fresh on order',
            actionLabel: 'Activate Special',
          },
          {
            tierNumber: 4,
            tierName: 'REDESIGN',
            title: 'Redesign menu: Add Tomato Pasta / Rasam',
            description: 'Replace standard clear broth with hearty fresh tomato rasam for all 185 thali trays.',
            isFeasible: true,
            impactScore: 'Consumes entire 6.8 kg surplus',
            safetyStatus: 'Approved by head chef',
            actionLabel: 'Update Menu Today',
          },
          {
            tierNumber: 5,
            tierName: 'REDISTRIBUTE',
            title: 'Redistribute to Robin Hood Army / Local Shelter',
            description: 'Schedule safe pickup for 3:30 PM with certified food redistribution partner.',
            isFeasible: true,
            impactScore: 'Zero landfill food waste',
            safetyStatus: 'Pre-certified hygiene protocol',
            actionLabel: 'Schedule Donation',
          },
          {
            tierNumber: 6,
            tierName: 'DISCARD',
            title: 'Discard spoiled stock',
            description: 'Compost bin. ONLY when all 5 prior rescue tiers are impossible or safety is compromised.',
            isFeasible: false,
            impactScore: 'Total loss (Avoid if possible)',
            safetyStatus: 'Biological waste only',
            actionLabel: 'Discard Food',
          },
        ],
      },
      {
        id: 'resc-2',
        ingredient: 'Fresh Paneer (Batch #PN-201)',
        emoji: '🥛',
        quantityAtRiskKg: 5.0,
        expiryHours: 24,
        currentRisk: 'CRITICAL',
        primarySuggestedTier: 'PROMOTE',
        status: 'pending',
        tiers: [
          {
            tierNumber: 1,
            tierName: 'USE',
            title: 'Add paneer cubes to vegetarian sabzi',
            description: 'Upgrade standard mixed veg to Aloo-Paneer without extra charge for 70 students.',
            isFeasible: true,
            impactScore: 'Rescues 3.5 kg',
            safetyStatus: 'Cooked at >75°C boiling',
            actionLabel: 'Add to Veg Sabzi',
          },
          {
            tierNumber: 2,
            tierName: 'ALLOCATE',
            title: 'Transfer to Staff Cafeteria Lounge',
            description: 'Staff lounge serves a-la-carte snacks; paneer tikka sells out daily.',
            isFeasible: true,
            impactScore: 'Rescues 2.0 kg',
            safetyStatus: 'Within campus premises',
            actionLabel: 'Transfer to Staff Lounge',
          },
          {
            tierNumber: 3,
            tierName: 'PROMOTE',
            title: 'Promote “Chef’s Paneer Special Roll”',
            description: 'Feature at snack counter at 4:30 PM at attractive price point.',
            isFeasible: true,
            impactScore: 'High popularity item (₹1,600 revenue saved)',
            safetyStatus: 'Cooked fresh on griddle',
            actionLabel: 'Launch Roll Special',
          },
          {
            tierNumber: 4,
            tierName: 'REDESIGN',
            title: 'Substitute Tofu for Paneer in evening gravy',
            description: 'Recipe swap saves high-cost inventory from expiry.',
            isFeasible: true,
            impactScore: 'Rescues 4 kg',
            safetyStatus: 'Standard culinary substitute',
            actionLabel: 'Swap Recipe',
          },
          {
            tierNumber: 5,
            tierName: 'REDISTRIBUTE',
            title: 'Redistribute according to organization safety norms',
            description: 'Deliver to community kitchen before 6 PM cutoff.',
            isFeasible: true,
            impactScore: 'Feeds 30 meals',
            safetyStatus: 'Cooler pack verified',
            actionLabel: 'Redistribute',
          },
          {
            tierNumber: 6,
            tierName: 'DISCARD',
            title: 'Discard only if sour or past safe temperature',
            description: 'Do not serve if sniff test or temperature log fails.',
            isFeasible: false,
            impactScore: 'Last resort only',
            safetyStatus: 'Safety inspection required',
            actionLabel: 'Log Spoiled',
          },
        ],
      },
    ],
    smartMenus: [
      {
        id: 'menu-1',
        dishName: 'Tomato Rasam & Artisanal Soup Bowl',
        emoji: '🍅',
        atRiskIngredient: 'Tomatoes (7 kg at risk)',
        ingredientUsageKg: 5,
        expectedPortions: 35,
        expectedWasteReductionKg: 3.5,
        reason: 'Tomatoes expire in 48 hours. Adding this bowl to today’s lunch menu absorbs 5 kg surplus with zero food waste.',
        status: 'pending',
      },
      {
        id: 'menu-2',
        dishName: 'Crispy Paneer Tikka Rolls',
        emoji: '🌯',
        atRiskIngredient: 'Paneer (8 kg near expiry)',
        ingredientUsageKg: 6,
        expectedPortions: 30,
        expectedWasteReductionKg: 5.5,
        reason: 'Paneer expires tomorrow. Feature as 4 PM evening tea snack special to eliminate ₹1,900 spoilage.',
        status: 'pending',
      },
      {
        id: 'menu-3',
        dishName: 'Spiced Buttermilk (Chaas)',
        emoji: '🥛',
        atRiskIngredient: 'Excess Curd / Yogurt',
        ingredientUsageKg: 8,
        expectedPortions: 50,
        expectedWasteReductionKg: 6.0,
        reason: 'High afternoon temperature creates high student demand for cool digestive drinks.',
        status: 'approved',
      },
    ],
    experiments: [
      {
        id: 'exp-1',
        title: '8% Lean Rice Production Test',
        emoji: '🍚',
        uncertaintyContext: 'Rice demand is uncertain by ±8%. On Mondays & Tuesdays, 2–3 kg was left over.',
        proposal: 'Reduce initial rice boiler production by 8% (from 24 kg to 22 kg) for the next 3 similar days.',
        hypothesis: 'Leftover rice will drop by 40%+ while 100% of customer orders are served without running short.',
        duration: '3 similar school days',
        controlGroup: 'Historical average production of 24.5 kg',
        testGroup: 'Lean batch of 22.0 kg with 2 kg dry buffer on standby',
        metrics: ['Sales volume', 'Kitchen leftovers (kg)', 'Stockout incidents (target 0)', 'Customer complaints'],
        status: 'suggested',
        learnedTakeaway: 'Tested in Block C: Reduced leftover rice by 44% without any stockouts or student wait time.',
        wasteReductionRecorded: '4.8 kg rice waste avoided across 3 days',
      },
      {
        id: 'exp-2',
        title: 'Two-Stage Chapati Rolling',
        emoji: '🫓',
        uncertaintyContext: 'Chapati demand fluctuates depending on late laboratory hours.',
        proposal: 'Prepare 60% of chapatis before 12:30 PM, roll remaining 40% fresh on demand as queues form.',
        hypothesis: 'Prevents dried-out discarded cold chapatis at 2:00 PM.',
        duration: '4 days',
        controlGroup: 'Cook all 380 chapatis at 11:30 AM',
        testGroup: '220 at 11:30 AM + 160 on live tawa',
        metrics: ['Cold discards', 'Tawa wait time', 'Electricity cost'],
        status: 'completed',
        learnedTakeaway: 'Zero dried chapatis discarded. Customer satisfaction jumped 18% due to piping hot food.',
        wasteReductionRecorded: '42 chapatis (3.5 kg flour) saved daily',
      },
    ],
    decisionReplays: [
      {
        id: 'rep-1',
        date: 'Yesterday (Mon)',
        item: 'Cooked Rice',
        aiPredicted: '20 kg',
        humanDecided: '23 kg',
        actualOutcome: '22.2 kg consumed (0.8 kg left)',
        difference: '+3 kg by Manager',
        reason: 'Manager knew about the visiting basketball tournament team.',
        evaluationNote: 'Human adjustment was correct! Prevented a food shortage during tournament rush.',
      },
      {
        id: 'rep-2',
        date: 'Last Friday',
        item: 'Chicken Curry',
        aiPredicted: '14 kg',
        humanDecided: '14 kg (Accepted AI)',
        actualOutcome: '13.8 kg consumed (0.2 kg left)',
        difference: '0 kg (Aligned)',
        reason: 'Followed FoodWise rainy day forecast.',
        evaluationNote: 'Accurate forecast: Waste was near zero (<200g).',
      },
      {
        id: 'rep-3',
        date: 'Last Thursday',
        item: 'Dal Fry',
        aiPredicted: '9 kg',
        humanDecided: '12 kg',
        actualOutcome: '8.8 kg consumed (3.2 kg left)',
        difference: '+3 kg by Manager',
        reason: 'Manager expected high walk-in traffic that did not materialize.',
        evaluationNote: 'AI prediction was closer to reality. Future days will remind manager of this pattern.',
      },
    ],
    leftoverHistory: [
      {
        date: 'Yesterday (Mon)',
        items: [
          { name: 'Rice', emoji: '🍚', predictedKg: 2.0, actualKg: 1.2, reason: 'Lower evening demand' },
          { name: 'Chicken Curry', emoji: '🍗', predictedKg: 1.0, actualKg: 2.3, reason: 'Prepared too much' },
          { name: 'Mixed Veg', emoji: '🥬', predictedKg: 3.0, actualKg: 0.8, reason: 'Customer preference' },
        ],
        learnedRule: 'Monday dinners have 12% lower grain intake. AI adjusted today’s baseline rice prep down.',
        nextForecastImpact: 'Rice reduced by 1.5 kg, chicken curry portion scaled down by 8%.',
      },
    ],
    damagedStock: [
      {
        id: 'dam-1',
        ingredient: 'Tomatoes',
        quantityKg: 2.5,
        reason: 'Spoiled',
        dateReported: '02 Oct 2026',
        recalculatedImpact: 'Available stock adjusted to 12 kg. Prevented counting spoiled stock towards dinner.',
      },
    ],
    weatherInfo: {
      city: 'Bengaluru, India',
      temperature: '26°C',
      condition: 'Rain expected this evening 🌧️',
      isRainExpected: true,
    },
    localNotice: cfg.notice,
  };
}
